### ISSUE TITLE
Sane defaults, +Core layers.

### ISSUE THREAD

**Issue by alexanderjeurissen** [Tehnix/spaceneovim#12]
I noticed that some sane defaults are not set for example, currently the configuration uses a tabwidth of 4, and no `expandtab` e.g. a tab character is used instead of the more common spaces for indentation.

I'd suggest that we adopt the sensible.vim package that comes with a lot of sane defaults that we can leverage. My suggestion would be to introduce a separate layer a `core` layer if you will. This will contain all the default settings and some core packages.

This also makes it easier to collaborate on default settings, when I tried to find the place where the leaderguide package was loaded I found out that it's defined here:
https://github.com/Tehnix/spaceneovim/blob/3d1d500ab3e853b8d4b080b54e0e5796dec10d4f/autoload/spaceneovim.vim#L145

That is not the place I would expect such `Plug` definitions to be defined. 

SpaceVim has a similar setting, where they use a `+core/behavior` layer that contains the following packages:

> editorconfig/editorconfig-vim
> haya14busa/incsearch.vim
> hecal3/vim-leader-guide
> kana/vim-arpeggio
> mhinz/vim-startify
> osyo-manga/vim-over
> Raimondi/delimitMate
> sheerun/vim-polyglot
> tpope/vim-sensible
> tpope/vim-surround

I think some of those should be moved to more specific layers for easy of discovery for new contributors. However stuff like editorconfig, vim-leader-guide and vim-startify are typical extensions that could be defined in a `core` layer.

@Tehnix Let me know your thoughts on this.

**Comment by lowski** [comment]
@alexanderjeurissen I started prototyping +core layer. Feel free to check it and share your thoughts.

**Comment by Tehnix** [comment]
I'll closed this since we've merged Tehnix/spaceneovim-layers#24
