### ISSUE TITLE
Error Updating spaceneovin layers

### ISSUE THREAD

**Issue by Vm900** [Tehnix/spaceneovim#14]
Hi folks,
Everytime i try to update the layers i keep getting the following errors:

Error detected while processing function OutputJobToBuffer:
E121: Undefined variable: self
E116: Invalid arguments for function nvim_buf_set_lines
-------------------------------------------------------------------------------------
Please Help 
Thanks in advance
PS Great tool BTW

**Comment by Tehnix** [comment]
This is an issue with `OutputJobToBuffer` first being added in a later version of Neovim. The current stable, `0.1.7` has this fixed.
