### ISSUE TITLE
Text missing gui

### ISSUE THREAD

**Issue by Vm900** [Tehnix/spaceneovim#15]
What could be going wrong here?I got everything setup according to the instruction but:
![snvim](https://cloud.githubusercontent.com/assets/9399631/21583422/d2dfaa7c-d077-11e6-85a1-74bbd9ee37af.png)

Ain't it supposed to be like this:
![snvim2](https://cloud.githubusercontent.com/assets/9399631/21583423/f28dd51a-d077-11e6-9323-d77b455a9819.png)
Please help
Thanx

**Comment by autoferrit** [comment]
I get the same issue

![image](https://cloud.githubusercontent.com/assets/89895/22118043/189c7b92-de2b-11e6-9277-e0dea98eab9f.png)

**Comment by Tehnix** [comment]
This should have been fixed in #17, try and update :)
