### ISSUE TITLE
No colors in tmux

### ISSUE THREAD

**Issue by harryio** [Tehnix/spaceneovim#16]
Running them on archlinux in gnome-terminal

**Comment by Tehnix** [comment]
I've no problem with colors in `tmux`. Are you still having issues, and if so, what version of `tmux` and `Neovim` are you running?

**Comment by harryio** [comment]
@Tehnix I'm using tmux 2.3.1 and nvim 0.1.7

**Comment by zacacollier** [comment]
@harryio are you still having this problem? colors in gnome-terminal + tmux can be prickly.. Try comparing the output of `echo $TERM` both inside and outside of `tmux`.

also, consider trying xfce4-terminal or termite. I've had better luck wrangling those in the past.

**Comment by zacacollier** [comment]
@harryio update: I actually just ran into this same problem whilst setting up a new work machine, and fixed it by placing these settings in my `.tmux.conf`:

```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
```

zap your tmux session with `tmux kill-server` and then restart. colors should work after that.

**Comment by jakswa** [comment]
fwiw I'm a regular tmux user (used for years, not much configuration experience), and have invested probably an hour trying to get colors working inside tmux on ubuntu, and have failed miserably. Somehow had it working fine in SpaceVim awhile back. Tried this thread's recommendation, as well as several other google hits. Even blew away my configs, tried to start fresh adding only what seemed to be needed.
