### ISSUE TITLE
vim-commentary and vim-surround does not work

### ISSUE THREAD

**Issue by lowski** [Tehnix/spaceneovim#19]
I've added [vim-commentary](https://github.com/tpope/vim-commentary/) and [vim-surround](https://github.com/tpope/vim-surround) to `g:dotspaceneovim_configuration_layers` but when I type i.e. `gcc` to comment the whole line nothing happens, the same if I try to operate on parenthesis (i.e. `cs"'` jumps to 23 lines).

@Tehnix any idea what can cause the issue?

**Comment by lowski** [comment]
@Tehnix any update on this?

**Comment by Tehnix** [comment]
Wokraround added as per #21
