### ISSUE TITLE
Loading layers from other repositories

### ISSUE THREAD

**Issue by quarterto** [Tehnix/spaceneovim#2]
It would be great if the layers repository URL was configurable and we could specify multiple URLs (so we could store personal config or hack on layers).

**Comment by Tehnix** [comment]
Great idea! For now I've added a variable `g:spaceneovim_layers_repository` that you can set in `init.vim` and added a bit of text on it in the readme.

As for pulling in multiple URLs, or potentially provide a git link directly to a layer, I'll have to look into a fitting approach on that. Definitely something I feel we should look into :)

**Comment by quarterto** [comment]
Perhaps that's something that could be done with Vim packages?

**Comment by autoferrit** [comment]
i like how zplug does this. 

Load a built in plugin, through the local directories
`zplug "[namespace]/[name]"`

Load a layer from a repo on github. Say someone forked the layers repo and added their own layer, you could install their version of a layer doing this.
`zplug "[username]/[reponame]", from:github, use:[layername] `

If it is a well known alternate layers repo, you could add direct support for them. like so
`zplug "[namespace]/[name]", from:[github-username]`

If the layer if nvim only:
`zplug "[namespace]/[name]", if:"[[ $OSTYPE == *darwin* ]]`

You would need to find the best way to convert those to vim syntax, but I think they could work. For the full listing of examples, go here https://github.com/zplug/zplug#example

**Comment by Tehnix** [comment]
I've added support for private layers finally. Now you can either point to your own layer repository, or simply add them in the `private` directory in the `spaceneovim-layers` folder.

I'll close this for now :)
