### ISSUE TITLE
How to change fontsize

### ISSUE THREAD

**Issue by Vm900** [Tehnix/spaceneovim#2]
Hi
How do i change font size coz it's really small

**Comment by Tehnix** [comment]
Hi!

Are you using a terminal or a GUI? In either case, the font size should be managed via either your terminals configuration, or whatever GUI you are using.

You might be able to just do `CTRL` + `SHIFT` + `+` / `CMD` + `SHIFT` + `+` to increase it. Alternatively, [set `guifont`](https://stackoverflow.com/a/17508781/701940) in your `~/.config/nvim/init.vim` settings file, in the [`UserConfig` block](https://github.com/Tehnix/spaceneovim#configuration).

**Comment by Vm900** [comment]
@Tehnix Thanx,changed the terminal font size and we're cooking
