### ISSUE TITLE
LanguageClient `no notification handler registered` errors

### ISSUE THREAD

**Issue by vviikk** [Tehnix/spaceneovim#3]
`no notification handler registered for "/Users/ramanujam/.config/nvim/plugged/La nguageClient-neovim/rplugin/python3/LanguageClient:autocmd:CursorMoved:*"`

In case anyone is facing errors like above, I fixed it with
```bash
# upgrade python bindings
pip install neovim
pip3 install neovim #python 2 is still default in my MacOS
```

Might want to add this to a troubleshooting section as I've faced this on Ubuntu, Arch and now MacOS.

**Comment by Tehnix** [comment]
It actually is covered in the install process https://github.com/Tehnix/spaceneovim#installation. That said, it might be worth mentioning the specific error and then the cause under https://github.com/Tehnix/spaceneovim#troubleshooting. 

Would you be up for making a PR for this?

EDIT: Ah, nvm! Just noticed your PR was exactly for this, thanks! :)
