### ISSUE TITLE
Questions about customization

### ISSUE THREAD

**Issue by lowski** [Tehnix/spaceneovim#6]
Hi!
I think I'm going to give a shot to this project over the weekend. I have a few beginner questions before I start:
1. How can I customize layer settings? I.e. I have those settings for Deoplete:
   
   ```
     " Close preview window after complition
     autocmd CompleteDone * pclose!
   
     let deoplete#tag#cache_limit_size = 5000000
     let g:deoplete#enable_at_startup = 1
     let g:deoplete#sources = {}
     let g:deoplete#sources._ = ['buffer', 'tag', 'ultisnips']
     let g:deoplete#sources.elixir = ['alchemist', 'buffer']
   ```
   
   Do I add those settings to my `init.vim` as usually or do I have to use some kind of `ftplugin`?
2. Is it possible to customize leader guide? For example I have the following shortcuts:
   
   ```
       let g:lmap[';'] = {
                          \'name': 'Meta',
                          \'i': ['PlugInstall', 'Install plugins'],
                          \'c': ['PlugClean', 'Clean plugins'],
                          \'u': ['PlugUpdate', 'Update plugins'],
                          \'U': ['PlugUpgrade', 'Upgrade manager']
                          \}
   ```
   
   In the future I also plan to add test runners for `rspec`, etc.
3. If I would like to create a new layer (I work mainly with `Rails` and `Ember.js` and keep learning `Elixir`) I just follow the convention like here https://github.com/Tehnix/spaceneovim-layers/blob/master/layers/%2Blang/javascript/config.vim, right?
4. Sorry for OT, what colorscheme (vim, terminal) is on the screenshot? 😄

**Comment by Tehnix** [comment]
Hey :)

I'll try to tackle the questions one-by-one:

1. It'd normally go into your init.vim, either inside the user-init block if it needs to run before loading plugins, or in the user-config block (most stuff goes here) if you want to run it after loading plugins. Since you are configuring deoplete, you'll want it in user-config.

2. Yeah, you can customize the leader guides, just as you normally would (i.e. put them in the user-config block). The only one that gets overwritten upon filetype change is `SPC m ` and everything under. All other bindings will be kept throughout, so yours should work with the code you posted.

3. I think the Haskell layer is probably the best example as of yet, since it's the only one I've really configured so far. If you want to add support for rails, I think we should make a layer at `layers/+frameworks/rails` and if there are any ruby general settings you can just add them to the existing `layer/+lang/ruby` layer :)

4. The colorscheme is `wombat256mod` which is included in vim-colorschemes :)

**Comment by dexafree** [comment]
I'll use this issue, as my questions are also related with customization:

1. Is it possible to change the leader key? I know it's called SPACEneovim (just as SPACEmacs), but I really like to have it mapped as ','. I've tried overriding the mapping made at `dotspaceneovim/init`, by replacing it to `let g:mapleader = ','`, but when I press it, it complains about "Key not present in dictionary" (really long stack trace) and it doesn't show guides. If you need more info, I can try to provide the full output.
2. Is there a way to reload changes made to a layer without actually restarting Neovim? I think it would be useful if a shortcut to "Reload the config files" could be made.
3. Is there any way to make a single character mapping? ie: `nmap <leader>eV :e ~/.config/nvim/init.vim`. I know the `e` group is already defined, it was just a quick example.

Thanks!

**Comment by lowski** [comment]
@Tehnix thanks for your reply.for

PS. It seems that neomake is started supporting vim8. Maybe it's a matter of time for deoplate to support vim8 as well :).

**Comment by Tehnix** [comment]
@dexafree Sorry for the slow reply!

1. Yeah it's possible, although it is a bit more involved than just setting the mapleader. Currently it is defined [here](https://github.com/Tehnix/spaceneovim-layers/blob/master/auto-layers.vim#L82), but making it a configurable setting shouldn't be much work - I'll look into it shortly :)
2. Hmm, I think sourcing $VIMRC should reload everything, there definitely needs to be an option to do that though.
3. You can take some inspiration from the [keybinding-helpers](https://github.com/Tehnix/spaceneovim-layers/blob/master/keybinding-helpers.vim#L26). I think something like

```viml
noremap <silent> <SID>a-new-binding# :echo "test"<CR>
nmap <Leader> e <SID>a-new-binding#
```
should do want you want - binding `SPC e` to the command `:echo "test" with the name "a-new-binding". It should automagically appear in the menu (although in this specific case with `e` it will probably get overwritten ;) )

4 . I actually haven't gotten around to implementing that as of yet. It would more or less just be extending the [layer discovery](https://github.com/Tehnix/spaceneovim/blob/master/autoload/spaceneovim.vim#L180). I should probably get that done very soon to make it easier to experiment with layers. At the moment you can either write directly to the directory or [set which repository it should take the layers from](https://github.com/Tehnix/spaceneovim#using-your-own-layer-repository).

@lowski That's awesome! I'm kinda waiting in excitement to see where both Syntastic and Neomake are going - I think Neomake was subtle waiting for Syntastic to add VIM8 async support and then adding neovim async support would be trivial after the architecture changes :)

**Comment by Tehnix** [comment]
With #9 and #10 closed, I'm gonna close this one too :)

Don't hesitate to open another issue if there are questions!
