### ISSUE TITLE
Group names not shown

### ISSUE THREAD

**Issue by dexafree** [Tehnix/spaceneovim#7]
When I press the leader key, the leader assistant shows up, but it only provides the name of the "definitive actions" (the action you are going to perform if you press that key).

I don't know if it's a bug, but it would be really great if the group names were shown, so you would not have to guess that `b` stands for Buffers.

Image showing the issue:

![](http://i.imgur.com/VwXBfzb.jpg)

**Comment by Tehnix** [comment]
That is definitely a bug! Could I ask what vim/neovim version you are on and if you have any other configuration in the file or experience any other errors?

It should by default show the names on all the groupings.

**Comment by dexafree** [comment]
Sure!
This is my configuration:
https://gist.github.com/dexafree/b29fc6f4e55ba24a96c650b2b30b9d68

The bindings, markdown lang, sneak and clever layers are just private layers for including some plugins or bindings.

The bug also happens if I comment those layers.

The neovim version is the following:

```
NVIM v0.1.6-182-g1984072
Build type: Dev
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161009-25254-17yw153/build/config -I/tmp/neovim-20161009-25254-17yw153/src -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/tmp/neovim-20161009-25254-17yw153/deps-build/usr/include -I/opt/local/include -I/usr/include -I/opt/local/include -I/tmp/neovim-20161009-25254-17yw153/build/src/nvim/auto -I/tmp/neovim-20161009-25254-17yw153/build/include
Compiled by XXXX@XXX-xXXX

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-1984072/share/nvim"

```

**Comment by belst** [comment]
I have the same problem:

Arch Linux
```
NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.6/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by NilujePerchut** [comment]
I also have the same problem from a brand new install.

Here follows more information about this problem.

After some debugs, it seems that the lmap dict is correctly generated and can be visualized using :echo g:lparam : 
````
{'q': {'name': '+quit'}, 'b': {'name': '+buffers'}, 't': {'name': '+toggles', 'h': {'name': '+highlight'}}, 'e':
 {'name': '+errors'}, 'f': {'name': '+files', 'e': {'name': 'spaceneovim/files'}}, 'w': {'name': '+windows'}, 'x
': {'name': '+text'}, 'm': {'name': '+major-mode-cmd'}}    
````

Adding the following line in init.vim bootstrap section makes the name appear:
`call leaderGuide#register_prefix_descriptions('<Space>', 'g:lmap')
`
I don't know why the same call in the postinstall section does not work. And I cannot see any way to solve this problem with a clean fix.

I hope this will help. Feel free to ask for more details

**Comment by lowski** [comment]
@NilujePerchut thanks for providing a working solution.

I also tried to debug this issu as well and it seems the problem is related to `leader-guide` plugin. If you add `call leaderGuide#register_prefix_descriptions('<Space>', 'g:lmap')` to `init.vim`, [this condition](https://github.com/hecal3/vim-leader-guide/blob/b1dd2667cb74147c06853c39530984fbc629eb48/plugin/leaderGuide.vim#L52) will fail and `leader-guide` won't call `call leaderGuide#register_prefix_descriptions('', 'g:leaderGuide_map')`. However `spaceneovim` call this function in `post_install` phase which is executed on `VimEnter` even. `VimEnter` is triggered after all `plugins/**/*.vim` are evaluated. That means `register_prefix_descriptions` is called from `leader-guide` first and then from `post_install` which mess things up.

@Tehnix any clean way to fix it?:) Maybe it would be better to call `post_install` manually from `init.vim` instead of relying on `VimEnter`. What do you think?

**Comment by Tehnix** [comment]
@lowski I think moving the `post_install` to `init.vim` might be the most consistent fix for now. I'll accept the #17 after the minor changes mentioned in that PR, which solves this problem.

**Comment by lowski** [comment]
@Tehnix I thought about it but then I come with the idea of having 3 phases:

- `preinistall`
- `postinstall`
- `postinit`

As I suggested in the PR. I think it's more flexible approach.
