### ISSUE TITLE
Don't set termguicolors

### ISSUE THREAD

**Issue by int-index** [Tehnix/spaceneovim#7]
These lines cause issues for me:

https://github.com/Tehnix/spaceneovim/blob/1feb755e7e7a6c1a3733bc68d2cc1e0e7f349396/autoload/spaceneovim.vim#L571-L573

![image](https://user-images.githubusercontent.com/4061728/48334482-e30d7800-e66b-11e8-9e76-4c607dc8c63e.png)

I can workaround by adding `set notermguicolors` to my `init.vim`, but it results in an unpleasant flash of cyan (like on the screenshot above) before I see proper colors.

Here are the colors I see if I remove these lines:

![image](https://user-images.githubusercontent.com/4061728/48334680-8b234100-e66c-11e8-905b-5d3db893f729.png)

I'm facing this issue on both the Xfce terminal and the macOS Terminal app.

**Comment by Tehnix** [comment]
I think if you set it manually instead of using e.g. `SetThemeWithBg 'dark', 'space-vim-dark', 'violet'`, there should be no problem.

I.e.

```
colorscheme 'space-vim-dark'
set background=dark
let g:airline_theme='violet'
```

with your own theme of course :)

**Comment by int-index** [comment]
Yes, that works. Thanks!
