### ISSUE TITLE
Add a note that oneliner in README will override original config

### ISSUE THREAD

**Issue by chuwy** [Tehnix/spaceneovim#8]
I just shot myself in a foot. I didn't realize that oneliner will override my original vimrc (I still cannot understand why). I have a link `~/.config/nvim/init.vim` which points to `~/.vimrc` which itself a link and points to `~/dotfiles/vimrc`. I thought oneliner will just replace link with downloaded file, but somehow it replaced original `~/dotfiles/vimrc` (I would lost it if I hadn't it in VCS). 

Also it would be nice to have instructions on how to start to spaceneovim for people who already have huge vimrc and many customized settings.

**Comment by dexafree** [comment]
It did override mine too (same setup with symlinks). Praise the VCS.

**Comment by Tehnix** [comment]
Hmm, I'm guessing curl writes directly to the file and therefore symlinks are also followed.

I've added a note about it, but perhaps a more involved install script would be better (i.e. one that automatically backs up existing configurations).
