### ISSUE TITLE
Question: Setting themes and fonts

### ISSUE THREAD

**Issue by slipsnip** [Tehnix/spaceneovim#8]
The Readme gives some examples of setting a theme under the heading "Customization" along with the command syntax but where can I find the list of theme names and airline themes to choose from.  Also regarding setting a font, being that I run nvim from terminal do I simply change the font my terminal emulator is using or is spaceneovim sourcing other fonts.

This is not an issue but I was unsure where to post my question and seen that there was another question posted here.

**Comment by Tehnix** [comment]
Hey!

> The Readme gives some examples of setting a theme under the heading "Customization" along with the command syntax but where can I find the list of theme names and airline themes to choose from.

You'll be able to find a list of VIM themes here https://vimcolors.com. You'll then need to find the repository it is in (you can click on them), and add it to your config to pull via

```viml
function! Layers()
  " ...
  ExtraPlugin 'liuchengxu/space-vim-dark'
endfunction
```

For AirLine themes, I think https://github.com/vim-airline/vim-airline-themes is the go to for that :)

> Also regarding setting a font, being that I run nvim from terminal do I simply change the font my terminal emulator is using or is spaceneovim sourcing other fonts.

Fonts will be controlled by the terminal, so you'll need to configure your terminal with your favorite font. If you are using a GUI you can [set it for that specifically though](https://vim.fandom.com/wiki/Change_font) in your `UserConfig` block (where most of your VIM configurations will go).

**Comment by slipsnip** [comment]
Thank you Tehnix you have been extremely helpful and this answers all of my questions perfectly.  I much appreciate your time and the awesome job you have done on spaceneovim.  I have experimented with other vim distributions and am finding this one to suit my use case the best.  Thanks

**Comment by Tehnix** [comment]
@slipsnip happy to hear it worked for you! :) I'll close this issue to clean up the issues list.
